"""
The MIT License (MIT)

Copyright (c) 2016 Amalia Gómez

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

__author__ = "Amalia Gomez"
__copyright__ = "Copyright 2016"
__license__ = "MIT"
__version__ = "1.0"
__email__ = "abeagomez@gmail.com"
__status__ = "Production"

import math
import VectorModel as VM

class BeliefNetwork():
	"""
	dict -> Dictionary: terms -> (doc -> times term appears in doc)
	docs -> Number of documents in database
	"""
	def __init__(self, terms, docs):
		self.N = docs
		self.Dictionary = terms

	"""
	the ordering of the retrieved documents (i.e., the ranking) defined by
	P(dj|q) coincides with the ordering generated by the vector model
	"""
	def P_dj_q(self, dj, q):
		vm = VM.VectorModel(self.Dictionary, self.N)
		Pk = (0.5)**(len(self.Dictionary))
		S = 0
		for ki in q:
			if dj in self.Dictionary[ki]:
				Pqk = vm.Wq(ki, q) / math.sqrt(sum([vm.Wq(kj, q)**2 for kj in self.Dictionary]))
				Pdk = vm.W(ki, dj) / math.sqrt(sum([vm.W(kj, dj)**2 for kj in self.Dictionary]))
				S += Pqk*Pdk*Pk
		return S

	def Rank(self, q):
		documents = {}
		for ki in self.Dictionary:
			for dj in self.Dictionary[ki]:
				if not dj in documents:
					documents[dj] = self.P_dj_q(dj, q)
		return documents



d = {"k1":{"d1":3, "d2":1}, "k2":{"d2":1, "d3":4}, "k3":{"d1":2, "d3":1}, "k4":{"d2":2, "d3":2}}
bn = BeliefNetwork(d, 3)
print(bn.Rank(["k1","k3"]))






